# Change these first
owner: 3flowcreative # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Aldanat Care
    url: https://aldanatcare.co.uk/
  - name: Amazon Tours Plan
    url: https://plan.amazontours.travel/
  - name: Blissful Care Homes
    url: https://blissfulcarehomes.com/
  - name: Calibration Select
    url: https://calibrationselect.co.uk/
  - name: CareTech Foundation
    url: https://www.caretechfoundation.org.uk/
  - name: Casterbridge Home Care
    url: https://casterbridgehomecare.co.uk/
  - name: Casterbridge Manor
    url: https://casterbridgemanor.co.uk/
  - name: Casterbridge Lodge
    url: https://casterbridgelodge.co.uk/
  - name: Capricorn Beach Cottages
    url: https://capricornbeachcottages.com/
  - name: Championing Social Care
    url: http://championingsocialcare.org.uk/
  - name: Golden Key Estates
    url: https://goldenkeyestates.co.uk/
  - name: Kent Finance
    url: https://kentfinance.co.uk/
  - name: Precious
    url: https://www.precious-homes.co.uk/
  - name: Phoenix Communications
    url: https://phoenixcommunications.co.uk/
  - name: Prominence Property
    url: https://prominenceproperty.co.uk/
  - name: Student Key Estates
    url: https://studentkeyestates.co.uk/
  - name: Wentworth Court
    url: http://wentworthct.com/

status-website:
  title: 3flowcreative Monitor
  baseUrl: /upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
