# Change these first
owner: 3flowcreative # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Precious
    url: https://www.precious-homes.co.uk/

status-website:
  baseUrl: /upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
